let suggestions = [
  "Abelia",
  "Aeonium", 
  "Aerangis Orchid",
  "African Violet",
  "Alocasia Frydek",
  "Alocasia Tiny Dancer",
  "Aloe Polyphylla",
  "Aloevera",
  "Asparagus Fern",
  "Ausmas Rose",
  "Barberton Daisy",
  "Beach Spider Lily",
  "Begonia",
  "Black Joker Siberian Iris",
  "Black-eyed Susan",
  "Blue Orchid",
  "Blue Violet",
  "Bunny Ear Cactus",
  "Bush Lily",
  "Calathea Orbifolia",
  "Calla Lily",
  "Cast Iron Plant",
  "China Rose",
  "Chocolate Soldier",
  "Cholla Cactus",
  "Chrysanthemum",
  "Coral Cactus",
  "Cyclamen Persicum",
  "Dahlia",
  "Dog Rose",
  "Drumstick Primrose",
  "Dutch Irises",
  "Echeveria Peacockii",
  "English Lavender",
  "False Shamrock",
  "Ficus Tineke",
  "French Lavender",
  "Gardenia",
  "Goat's Horn Cactus",
  "Gerbera Daisy",
  "Gertrude Jekyll",
  "Goat’s Horn Cactus",
  "Golden Barrel Cactus",
  "Hardy Fuchsia",
  "Hawaiian Ti",
  "Hibiscus",
  "Hoya Kerrii", 
  "Hydrangea",
  "Inch Plant",
  "Iris Foetidissima",
  "Iris Virginica",
  "Jade Plant",
  "Japanese Camelia",
  "Japanese Water Iris",
  "Jersey Lily",
  "Kalanchoe Thyrsiflora",
  "Lithops Pesudotrucatella",
  "Lucky Bamboo",
  "Lycaste Orchid",
  "Lycoris Radiata",
  "Madagascar Jasmine",
  "Maidenhair Fern",
  "Marigold",
  "Miltonia Orchid",
  "Mini Monstera",
  "Moth Orchid",
  "Mr.Lincoln Rose",
  "Neoregelia Carolinae",
  "Pachira",
  "Paphiopedilum Concolor",
  "Periwinkle",
  "Peruvian Zinnia",
  "Petunia",
  "Philodendron Birkin",
  "Phlox",
  "Pilea Peperomioides",
  "Pink Quill",
  "Poinsettia",
  "Poison Primrose",
  "Pothos",
  "Purple Hellebore",
  "Queens Tears", 
  "Rubber Plant",
  "Sago Palm",
  "Slipper Orchid",
  "Snake Plant",
  "Spider Plant",
  "Strelitzia Reginae",
  "Schlumbergera",
  "Sunflower",
  "Tulip Negrita",
  "Urn Plant",
  "Venus Fly Trap",
  "Vriesea Splendens",
  "Weeping Fig",
  "White Trillium",
  "Yucca",
  "Zebra Plant",
  "Zinderella",
  "Zygopetalum Orchid",
];